### ISSUE TITLE
Server completely stops while downloading images

### ISSUE THREAD

**Issue by Vontus** [egold555/UrlToBlock#1]
When using the command /ub add, the server stops running until it finishes downloading the image you requested. This is specially noticeable when downloading big images. Maybe you should create another thread when making the http request.

**Comment by egold555** [comment]
Yes, the problem when doing async tasks in bukkit/spigot is if you call tasks (like giving the player a item) the server seems to have 50/50 chance of crashing. I will look into it though

**Comment by Vontus** [comment]
Maybe, if the image is too big, an idea could be to download it in a sencodary thread and notify the player when the download has finished. Then they should perform another action like sending a command or pressing on a text message in the chat to receive the block. That way you can give the block to the player in the main thread and prevent the server from crashing.

**Comment by egold555** [comment]
This will be in the next update.
https://github.com/egold555/UrlToBlock/commit/8a9dc12c5f84cef559f8a40837ae74512c6588b7

**Comment by egold555** [comment]
Fixed.
